-- Brazilian Portuguese, nomadbr on CurseForge

FishingTranslations["ptBR"] = {
	ABOUT_TAB = "Sobre", -- Needs review
	ADDFISHIEMSG = "Adicionando %s para a localiza\195\167\195\163o %s.",
	ADDSCHOOLMSG = "Adicionando '%s' para a localiza\195\167\195\163o %s.",
	ALLZOMGPETS = "Incluir todos os mascotes", -- Needs review
	BINDING_NAME_FISHINGBUDDY_GOFISHING = "Vista-se e v\195\161 pescar",
	BINDING_NAME_FISHINGBUDDY_SWITCH = "Mudar Equipamento de Pesca",
	BINDING_NAME_FISHINGBUDDY_TOGGLE = "Alternar a Janela  do #NAME#", -- Needs review
	BINDING_NAME_TOGGLEFISHINGBUDDY_LOC = "Alternar o Painel de Localiza\195\167\195\163o do #NAME#", -- Needs review
	BINDING_NAME_TOGGLEFISHINGBUDDY_OPT = "Alternar o Painel de Op\195\167\195\181es do #NAME#", -- Needs review
	BOBBER_NAME = "Isca de Pesca",
	CAUGHT_IN_ZONES = "Capturados em: %s",
	CAUGHTTHISMANY = "Capturados:",
	CAUGHTTHISTOTAL = "Total:",
	CLEANUP_DONEMSG = "Configura\195\167\195\181es antigas removidas para |c#RED#%s|r: %s.",
	CLEANUP_NONEMSG = "Nenhuma configura\195\167\195\163o antiga permanece.",
	CLEANUP_NOOLDMSG = "N\195\163o h\195\161 configura\195\167\195\181es antigas para o jogador |c#GREEN#%s|r.",
	CLEANUP_WILLMSG = "Configura\195\167\195\181es antigas remanescentes para |c#RED#%s|r: %s.",
	CLICKTOSWITCH_INFO = "Se ativado, um clique com o bot\195\163o esquerdo muda os equipamentos, caso contr\195\161rio ele abre a janela do Fishing Buddy",
	CLICKTOSWITCH_ONOFF = "Clique para mudar",
	COMPATIBLE_SWITCHER = "Nenhum alternador de equipamentos compat\195\173vel encontrado.",
	CONFIG_ALWAYSLURE_INFO = "Se habilitado, coloca uma isca toda vez que a vara n\195\163o tiver uma.",
	CONFIG_ALWAYSLURE_ONOFF = "Sempre com Isca",
	CONFIG_AUTOLOOT_INFO = "Se habilitado, o saque autom\195\161tico \195\169 habilitado enquanto pesca.",
	-- CONFIG_AUTOLOOT_INFOD = "Automatic looting is disabled because FishWarden is turned on.",
	CONFIG_AUTOLOOT_ONOFF = "Saque Autom\195\161tico",
	CONFIG_AUTOOPEN_INFO = "Se ativado, use o clique duplo para abrir itens de miss\195\181es de pescaria.", -- Needs review
	CONFIG_AUTOOPEN_ONOFF = "Abrir itens de miss\195\181es", -- Needs review
	CONFIG_BGSOUNDS_INFO = "Se ativado, o som ser\195\161 habilitado enquanto WoW est\195\161 em segundo plano.",
	CONFIG_BGSOUNDS_ONOFF = "Som de fundo",
	-- CONFIG_BOBBINGBERG_INFO = "If enabled, using the bobbing berg.",
	CONFIG_CONTESTS_INFO = "Exibe cron\195\180metros para competi\195\167\195\181es de pescaria.", -- Needs review
	CONFIG_CONTESTS_ONOFF = "Suporte a competi\195\167\195\181es de pescaria", -- Needs review
	-- CONFIG_CREATEMACRO_INFO = "Create a macro that performs #NAME# functions.",
	-- CONFIG_CREATEMACRO_ONOFF = "Create macro",
	CONFIG_DERBYTIMER_INFO = "Se ativado, exibe uma contagem regressiva para o in\195\173cio do Campeonato de Pesca dos Kalu'ak e uma contagem regressiva do tempo restante.", -- Needs review
	CONFIG_DERBYTIMER_ONOFF = "Cron\195\180metro do Campeonato", -- Needs review
	CONFIG_DINGQUESTFISH_INFO = "Se ativado, o som de miss\195\163o adicionada ir\195\161 tocar quando um peixe que d\195\161 reputa\195\167\195\163o com Nat Pagle \195\169 capturado.", -- Needs review
	CONFIG_DINGQUESTFISH_ONOFF = "Alarme de Peixe", -- Needs review
	CONFIG_DRINKHEAVILY_INFO = "Se ativado, bebe #LAGER# sempre que voc\195\170 estiver 'seco' e pescando.", -- Needs review
	CONFIG_DRINKHEAVILY_ONOFF = "Beber Lager", -- Needs review
	CONFIG_EASYCAST_INFO = "Ativa o lan\195\167amento com duplo-clique direito", -- Needs review
	CONFIG_EASYCAST_INFOD = "Lan\195\167amento f\195\161cil est\195\161 desabilitado porque Fishing Ace! est\195\161 ligado.", -- Needs review
	-- CONFIG_EASYCASTKEYS_INFO = "If a modifier key is specified, then when it is down, regardless of fishing gear.",
	CONFIG_EASYCAST_ONOFF = "Lan\195\167amento F\195\161cil",
	CONFIG_EASYLURES_INFO = "Se ativado, uma isca ser\195\161 aplicada \195\160 sua vara de pesca antes de come\195\167ar a pesca, sempre que voc\195\170 precisar de uma.",
	CONFIG_EASYLURES_ONOFF = "Iscas F\195\161ceis",
	CONFIG_ENHANCESOUNDS_INFO = "Quando ativado, maximiza o volume do som e minimiza o volume do ambiente para tornar o barulho da b\195\179ia mais percept\195\173vel enquanto pesca.",
	CONFIG_ENHANCESOUNDS_ONOFF = "Melhorar os sons de pesca",
	CONFIG_FINDFISH_INFO = "Liga a habilidade 'Localizar Peixes' quando vestido para pescar.",
	CONFIG_FINDFISH_ONOFF = "Localizar Peixes",
	CONFIG_FISHINGBUDDY_INFO = "Traga aquele amigo especial enquanto voc\195\170 pesca.", -- Needs review
	CONFIG_FISHINGBUDDY_ONOFF = "Fishing Buddy", -- Needs review
	CONFIG_FISHINGCHARM_INFO = "Se ativado, usa o talism\195\163 de pesca quando estiver em Pandaria.", -- Needs review
	CONFIG_FISHINGFLUFF_INFO = "Ativa todo tipo de divers\195\163o enquanto voc\195\170 pesca.", -- Needs review
	CONFIG_FISHINGFLUFF_ONOFF = "Divers\195\163o na Pescaria", -- Needs review
	-- CONFIG_FISHINGRAFT_INFO = "If enabled, use the fishing raft.",
	CONFIG_FISHWATCH_INFO = "Exibe um texto sobreposto com o peixe pescado no local atual.",
	CONFIG_FISHWATCHONLY_INFO = "Exibe o Observador de Peixes apenas quando estivermos de fato pescando", -- Needs review
	CONFIG_FISHWATCHONLY_ONOFF = "Somente enquanto pesca",
	CONFIG_FISHWATCH_ONOFF = "Observador de peixes",
	CONFIG_FISHWATCHPAGLE_INFO = "Exibe qual peixe de miss\195\163o do Pagle voc\195\170 capturou hoje.", -- Needs review
	CONFIG_FISHWATCHPAGLE_ONOFF = "Atentar a Peixes do Pagle", -- Needs review
	CONFIG_FISHWATCHPERCENT_INFO = "Exibe a porcentagem de cada tipo de peixe no visualizador.", -- Needs review
	CONFIG_FISHWATCHPERCENT_ONOFF = "Exibir porcentagens", -- Needs review
	CONFIG_FISHWATCHSKILL_INFO = "Exibe a per\195\173cia de pesca atual e mods na \195\161rea de visualiza\195\167\195\163o de peixes", -- Needs review
	CONFIG_FISHWATCHSKILL_ONOFF = "Per\195\173cia atual",
	CONFIG_FISHWATCHTIME_INFO = "Exibe a quantidade de tempo desde a \195\186ltima vez que voc\195\170 equipou uma vara de pesca", -- Needs review
	CONFIG_FISHWATCHTIME_ONOFF = "Exibir o tempo decorrido", -- Needs review
	CONFIG_FISHWATCHZONE_INFO = "Exibe a zona atual na \195\161rea de visualiza\195\167\195\163o de peixes.", -- Needs review
	CONFIG_FISHWATCHZONE_ONOFF = "Zona atual",
	-- CONFIG_LASTRESORT_INFO = "If enabled, add the biggest lure we have even if it doesn't get us to 100% chance of a catch.",
	-- CONFIG_LASTRESORT_ONOFF = "Lure of last resort",
	-- CONFIG_MAINTAINBERG_INFO = "If enabled, do not use the bobbing berg item, only maintain it if it is already being used.",
	-- CONFIG_MAINTAINRAFTBERG_ONOFF = "Maintain only",
	-- CONFIG_MAINTAINRAFT_INFO = "If enabled, do not use the raft item, only maintain it if it is already being used.",
	CONFIG_MAXSOUND_INFO = "Se ativado, deixa o volume no m\195\161ximo enquanto estiver pescando.", -- Needs review
	CONFIG_MAXSOUND_ONOFF = "Volume M\195\161ximo", -- Needs review
	CONFIG_MINIMAPBUTTON_INFO = "Exibe um \195\173cone do #NAME# no mini-mapa.",
	CONFIG_MINIMAPBUTTON_ONOFF = "Exibir \195\173cone no mini-mapa", -- Needs review
	CONFIG_MINIMAPMOVE_INFO = "Se ativado, o \195\173cone do mini-mapa pode ser movido arrastando-o.", -- Needs review
	CONFIG_MINIMAPMOVE_ONOFF = "Arrast\195\161vel", -- Needs review
	CONFIG_MOUNTEDCAST_INFO = "Se ativado, permite o lan\195\167amento enquanto estiver montado.", -- Needs review
	CONFIG_MOUNTEDCAST_ONOFF = "Montado", -- Needs review
	-- CONFIG_MOUSEEVENT_INFO = "Use this mouse button to cast.",
	-- CONFIG_MOUSEEVENT_ONOFF = "Casting Button",
	-- CONFIG_ONLYMINE_INFO = "If enabled, easy cast will only check for your outfit's fishing pole (i.e. it won't search all possible poles for a match).",
	-- CONFIG_ONLYMINE_ONOFF = "Outfit Pole Only",
	-- CONFIG_OUTFITTER_TEXT = "Outfit skill bonus: %s#BR#Draznar's style score: %d ",
	CONFIG_PARTIALGEAR_INFO = "Se ativado, lan\195\167a quando estiver vestindo qualquer equipamento de pescaria, mesmo se uma vara n\195\163o estiver equipada.", -- Needs review
	CONFIG_PARTIALGEAR_ONOFF = "Equipamento Parcial", -- Needs review
	-- CONFIG_PREVENTRECAST_INFO = "Invoking the macro while fishing will not cast again. Lures will be reapplied if needed.",
	-- CONFIG_PREVENTRECAST_ONOFF = "Prevent recast",
	CONFIG_SHOWLOCATIONZONES_INFO = "Exibe \195\162mbas zonas e subzonas.", -- Needs review
	CONFIG_SHOWLOCATIONZONES_ONOFF = "Exibir Zonas", -- Needs review
	CONFIG_SHOWNEWFISHIES_INFO = "Exibe uma mensagem na janela de bate-papo quando um novo peixe \195\169 capturado para a localiza\195\167\195\163o atual.", -- Needs review
	CONFIG_SHOWNEWFISHIES_ONOFF = "Exibir novo peixe", -- Needs review
	-- CONFIG_SHOWPOOLS_INFO = "If enabled, known pool locations will be displayed on the minimap.",
	-- CONFIG_SHOWPOOLS_ONOFF = "Show pools",
	CONFIG_SORTBYPERCENT_INFO = "Ordena visualiza\195\167\195\181es pelo n\195\186mero de peixes capturados ao inv\195\169s do nome.", -- Needs review
	CONFIG_SORTBYPERCENT_ONOFF = "Ordenar por n\195\186meros capturados", -- Needs review
	-- CONFIG_SPARKLIES_INFO = "If enabled, the 'sparkles' on fishing pools will be more visible while fishing.",
	-- CONFIG_SPARKLIES_ONOFF = "Enhance Pools",
	-- CONFIG_STVPOOLSONLY_INFO = "If enabled, easy cast will only be enabled if the cursor is over a fishing hole.",
	-- CONFIG_STVPOOLSONLY_ONOFF = "Only cast in pools",
	CONFIG_STVTIMER_INFO = "Se ativado, exibe uma contagem regressiva para o in\195\173cio do Fester\195\170 de Pesca e uma contagem regressiva do tempo restante.", -- Needs review
	CONFIG_STVTIMER_ONOFF = "Cron\195\180metro do Fester\195\170", -- Needs review
	-- CONFIG_TOOLTIPS_INFO = "If enabled, information about caught fish will be displayed in item tooltips.",
	-- CONFIG_TOOLTIPS_ONOFF = "Show fishing info in tooltips",
	-- CONFIG_TOONMACRO_INFO = "Create the fishing macro per player.",
	-- CONFIG_TOONMACRO_ONOFF = "Per player",
	CONFIG_TURNOFFPVP_INFO = "Se ativado, JxJ ser\195\161 desligado quando uma vara de pesca \195\169 equipada.", -- Needs review
	CONFIG_TURNOFFPVP_ONOFF = "Desligar JxJ", -- Needs review
	CONFIG_TURNONSOUND_INFO = "Se ativado, sempre liga os sons enquanto estiver pescando.", -- Needs review
	CONFIG_TURNONSOUND_ONOFF = "For\195\167ar som", -- Needs review
	-- CONFIG_TUSKAARSPEAR_INFO = "If enabled, do the complicated dance to use the Tuskaar Spear.",
	CONFIG_USEACTION_INFO = "Se ativado, #NAME# ir\195\161 procurar por um bot\195\163o da barra de a\195\167\195\181es para usar para lan\195\167amento.", -- Needs review
	CONFIG_USEACTION_ONOFF = "Usar A\195\167\195\163o", -- Needs review
	-- CONFIG_WATCHBOBBER_INFO = "If enabled, #NAME# will not cast if the cursor is over the Fishing Bobber.",
	-- CONFIG_WATCHBOBBER_ONOFF = "Watch bobber",
	COPPER_COIN = "Moeda de Cobre", -- Needs review
	CURRENT_HELP = "|c#GREEN#/fb #CURRENT# #RESET#|r#BRSPCS#Reinicia os peixes capturados durante a sess\195\163o atual.", -- Needs review
	DERBY = "Campeonato", -- Needs review
	DESCRIPTION1 = "Mant\195\169m o controle dos peixes que voc\195\170 capturou", -- Needs review
	DESCRIPTION2 = "e gerencia seu equipamento de pesca.", -- Needs review
	ELAPSED = "Decorrido", -- Needs review
	-- ELDER_CLEARWATER = "Elder Clearwater yells: (%a)+ has won the Kalu'ak Fishing Derby!",
	ELEM_WATER = "\195\129gua Elemental", -- Needs review
	EXTRAVAGANZA = "Fester\195\170", -- Needs review
	FAILEDINIT = "N\195\163o inicializou corretamente.", -- Needs review
	FATLADYSINGS = "|c#RED#%s acabou|r (%d:%02d restante)", -- Needs review
	FISH = "Peixe", -- Needs review
	-- FISHINGMODE_HELP = "|c#GREEN#/fb #FISHINGMODE# [start|stop]|r#BRSPCS#Run #NAME# fishing actions.#BRSPCS#Useful in macros along with '/cast Fishing'.",
	FISHTYPES = "Tipos de peixe: %d", -- Needs review
	-- FLOATING_DEBRIS = "Floating Debris",
	-- FLOATING_WRECKAGE = "Floating Wreckage",
	GOLD_COIN = "Moeda de Ouro", -- Needs review
	HIDEINWATCHER = "Exibir este peixe no observador", -- Needs review
	KEYS_ALT_TEXT = "Alt", -- Needs review
	KEYS_CTRL_TEXT = "Control", -- Needs review
	KEYS_LABEL_TEXT = "Modificadores:", -- Needs review
	KEYS_NONE_TEXT = "Nenhum", -- Needs review
	KEYS_SHIFT_TEXT = "Shift", -- Needs review
	LAGER = "Lager do Capit\195\163o Rumsey", -- Needs review
	LEFTCLICKTODRAG = "Clique com o bot\195\163o esquerdo para arrastar", -- Needs review
	LOCATIONS_INFO = "Exibe onde voc\195\170 capturou peixe seja por \195\129rea ou Tipo de Peixe", -- Needs review
	LOCATIONS_TAB = "Localiza\195\167\195\181es", -- Needs review
	-- MACRONAME = "FishingBuddy",
	MINIMAPBUTTONPLACEMENT = "Fixa\195\167\195\163o", -- Needs review
	MINIMAPBUTTONPLACEMENTTOOLTIP = "Permite que voc\195\170 mova o \195\173cone do #NAME# ao redor do mini-mapa.", -- Needs review
	MINIMAPBUTTONRADIUS = "Dist\195\162ncia", -- Needs review
	MINIMAPBUTTONRADIUSTOOLTIP = "Determina o qu\195\163o distante o \195\173cone do #NAME# deve ficar do mini-mapa.", -- Needs review
	MINIMUMSKILL = "Per\195\173cia m\195\173nima: %d", -- Needs review
	NAME = "Fishing Buddy", -- Needs review
	-- NOCREATEMACROGLOB = "Could not create global macro: ",
	-- NOCREATEMACROPER = "Could not create per character macro: ",
	NODATAMSG = "Sem dados de pescaria dispon\195\173vel.", -- Needs review
	NONEAVAILABLE_MSG = "Nenhum dispon\195\173vel", -- Needs review
	NOREALM = "reino desconhecido", -- Needs review
	NOTLINKABLE = "<item n\195\163o \195\169 link\195\161vel>", -- Needs review
	-- OFFSET_LABEL_TEXT = "Offset:",
	-- OIL_SPILL = "Oil Spill",
	OPTIONS_INFO = "Define as op\195\167\195\181es do #NAME#", -- Needs review
	OPTIONS_TAB = "Op\195\167\195\181es", -- Needs review
	OUTFITS = "Equipamentos", -- Needs review
	POINT = "ponto", -- Needs review
	POINTS = "pontos", -- Needs review
	-- POST_HELP = "You can bind both the window toggle and the outfit#BR#switch command to keys in the \"Key Bindings\" window.",
	-- PRE_HELP = "You can use |c#GREEN#/fishingbuddy|r or |c#GREEN#/fb|r for all commands#BR#|c#GREEN#/fb|r: by itself, toggle the Fishing Buddy window#BR#|c#GREEN#/fb #HELP#|r: display this message",
	RANDOM = "Aleat\195\179rio", -- Needs review
	RAW = "cru", -- Needs review
	-- RIGGLE_BASSBAIT = "Riggle Bassbait yells: We have a winner! (%a+) is the Master Angler!",
	RIGHTCLICKFORMENU = "Clique com o direito para o menu", -- Needs review
	-- ROLE_ADDON_AUTHORS = "AddOn Author of Note",
	ROLE_HELP_BUGS = "Corre\195\167\195\181es de bugs e ajuda na codifica\195\167\195\163o", -- Needs review
	ROLE_HELP_SUGGESTIONS = "Sugest\195\163o de funcionalidades", -- Needs review
	ROLE_TRANSLATE_DEDE = "Tradu\195\167\195\163o Alem\195\163", -- Needs review
	ROLE_TRANSLATE_ESES = "Tradu\195\167\195\163o Espanhola", -- Needs review
	ROLE_TRANSLATE_FRFR = "Tradu\195\167\195\163o Francesa", -- Needs review
	ROLE_TRANSLATE_ITIT = "Tradu\195\167\195\163o Italiana", -- Needs review
	ROLE_TRANSLATE_KOKR = "Tradu\195\167\195\163o Koreana", -- Needs review
	ROLE_TRANSLATE_PTBR = "Tradu\195\167\195\163o Portuguesa (Brasileiro)", -- Needs review
	ROLE_TRANSLATE_RURU = "Tradu\195\167\195\163o Russa", -- Needs review
	ROLE_TRANSLATE_ZHCN = "Tradu\195\167\195\163o Chinesa (Simplificado)", -- Needs review
	ROLE_TRANSLATE_ZHTW = "Tradu\195\167\195\163o Chinesa (Tradicional)", -- Needs review
	-- SCHOOL = "School",
	SHOWFISHIES = "Exibir peixe", -- Needs review
	SHOWFISHIES_INFO = "Exibe o hist\195\179rico de pescaria agrupado por tipo de peixe.", -- Needs review
	SHOWLOCATIONS = "Localiza\195\167\195\181es", -- Needs review
	SHOWLOCATIONS_INFO = "Exibe o hist\195\179rico de pescaria agrupado por \195\161rea de captura.", -- Needs review
	SILVER_COIN = "Moeda de Prata", -- Needs review
	STVZONENAME = "Selva do Espinha\195\167o", -- Needs review
	-- SWITCH_HELP = "|c#GREEN#/fb #SWITCH#|r#BRSPCS#swap outfits (if OutfitDisplayFrame or Outfitter is available)",
	THANKS = "Obrigado a todos!", -- Needs review
	TIMELEFT = "%s termina em %d:%02d", -- Needs review
	-- TIMERRESET_HELP = "|c#GREEN#/fb #TIMER# #RESET#|r#BRSPCS#Reset the location of the Extravaganza timer by moving it to#BRSPCS#the middle of the screen.",
	TIMETOGO = "%s come\195\167a em %d:%02d", -- Needs review
	TOOLTIP_HINT = "Dica:", -- Needs review
	TOOLTIP_HINTSWITCH = "clique para trocar equipamentos", -- Needs review
	TOOLTIP_HINTTOGGLE = "clique para exibir a janela do #NAME#", -- Needs review
	TOOMANYFISHERMEN = "Voc\195\170 tem mais de um mod de lan\195\167amento f\195\161cil instalado.", -- Needs review
	TOTAL = "Total", -- Needs review
	TOTALS = "Totais", -- Needs review
	-- UPDATEDB_HELP = "|c#GREEN#/fb #UPDATEDB# [#FORCE#]|r#BRSPCS#Try and find the names of all the fish we don't know already.#BRSPCS#An attempt is made to skip 'rare' fish that may disconnect you#BRSPCS#from the server -- use the '#FORCE#' option to override the check.",
	UPDATEDB_MSG = "Atualizou %d nomes de peixe.", -- Needs review
	-- WATCHER_HELP = "|c#GREEN#/fb #WATCHER#|r [|c#GREEN##WATCHER_LOCK#|r or |c#GREEN##WATCHER_UNLOCK#|r or |c#GREEN##RESET#|r]#BRSPCS#Unlock the watcher to move the window,#BRSPCS#lock to stop, reset to reset",
	WATCHER_TAB = "Observador", -- Needs review
}